# Convolutional Neural Net for Image Classification

## Import Libraries

In [1]:
import numpy as np
# Keras module layer
from keras.models import Sequential
# Keras core layers
from keras.layers import Dense, Dropout, Activation, Flatten
# Keras CNN layers
from keras.layers import Conv2D, MaxPooling2D
# Keras utilities
from keras.utils import np_utils

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


## Load Image Data

In [2]:
# MNIST data
from keras.datasets import mnist

# Load pre shuffled data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
print(X_train.shape)

(60000, 28, 28)


In [4]:
# Plotting the first sample of the dataset
import matplotlib.pyplot as plt
plt.imshow(X_train[0])

## Preprocessing Input Data

In [5]:
# Reshaping the input data to declare depth of 1 (n, depth, width, height)
X_train = X_train.reshape(X_train.shape[0], 1, 28, 28)
X_test = X_test.reshape(X_test.shape[0], 1, 28, 28)

print(X_train.shape)

(60000, 1, 28, 28)


In [6]:
# Converting the d-types to float
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255

## Preprocess Label Data

In [7]:
print(y_train.shape)

(60000,)


In [8]:
print(y_train[:10])

[5 0 4 1 9 2 1 3 1 4]


In [9]:
# Convert the 1-dim array into 10 distinct class matrices 
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)

In [10]:
print(y_train.shape)
print(y_train[:10])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


## Defining Model Architecture

In [11]:
# Sequential Model
model = Sequential()

In [24]:
# Input Layer
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(1,28,28), data_format='channels_first'))

model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))


## Compile The Model

In [25]:
model.compile(loss='categorical_crossentropy',
              optimizer='adam', 
              metrics=['accuracy'])

## Fitting the model on the training data

In [28]:
# model.fit(X_train, y_train, batch_size=200, 
#           epochs=2, 
#           verbose=1)

Epoch 1/2
60000/60000 [==============================] - 121s 2ms/step - loss: 0.0804 - acc: 0.9777
Epoch 2/2
60000/60000 [==============================] - 122s 2ms/step - loss: 0.0648 - acc: 0.9800


## Test Data Eval

In [29]:
score = model.evaluate(X_test, y_test, verbose=0)

In [31]:
print('Loss:',score[0], 'Accuracy:', score[1])

Loss: 0.03246637214660295 Accuracy: 0.9887
